// Extended book catalog - 205 books all priced over ₹100
// Categories: Fiction, Non-Fiction, Science Fiction, Fantasy, Mystery & Thriller, Romance, Biography, Technology, Science, Young Adult

const categories = {
  fiction: { id: "cat-fiction", name: "Fiction", slug: "fiction", createdAt: new Date() },
  nonFiction: {
    id: "cat-non-fiction",
    name: "Non-Fiction",
    slug: "non-fiction",
    createdAt: new Date(),
  },
  sciFi: {
    id: "cat-science-fiction",
    name: "Science Fiction",
    slug: "science-fiction",
    createdAt: new Date(),
  },
  fantasy: { id: "cat-fantasy", name: "Fantasy", slug: "fantasy", createdAt: new Date() },
  mystery: {
    id: "cat-mystery-thriller",
    name: "Mystery & Thriller",
    slug: "mystery-thriller",
    createdAt: new Date(),
  },
  romance: { id: "cat-romance", name: "Romance", slug: "romance", createdAt: new Date() },
  biography: { id: "cat-biography", name: "Biography", slug: "biography", createdAt: new Date() },
  technology: {
    id: "cat-technology",
    name: "Technology",
    slug: "technology",
    createdAt: new Date(),
  },
  science: { id: "cat-science", name: "Science", slug: "science", createdAt: new Date() },
  youngAdult: {
    id: "cat-young-adult",
    name: "Young Adult",
    slug: "young-adult",
    createdAt: new Date(),
  },
};

export const demoBooks = [
  // ═══════════════════════════════════════════════════
  // FICTION (30 books)
  // ═══════════════════════════════════════════════════
  {
    id: "f-1",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    price: "713",
    image: "https://covers.openlibrary.org/b/isbn/9781250301697-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-15"),
    category: categories.fiction,
  },
  {
    id: "f-2",
    title: "Dune",
    author: "Frank Herbert",
    price: "215",
    image: "https://covers.openlibrary.org/b/isbn/9780441172719-L.jpg",
    rating: 4.8,
    createdAt: new Date("2026-01-14"),
    category: categories.fiction,
  },
  {
    id: "f-3",
    title: "The Alchemist",
    author: "Paulo Coelho",
    price: "299",
    image: "https://covers.openlibrary.org/b/isbn/9780061122415-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-13"),
    category: categories.fiction,
  },
  {
    id: "f-4",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    price: "349",
    image: "https://covers.openlibrary.org/b/isbn/9780060935467-L.jpg",
    rating: 4.8,
    createdAt: new Date("2026-01-12"),
    category: categories.fiction,
  },
  {
    id: "f-5",
    title: "1984",
    author: "George Orwell",
    price: "279",
    image: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-11"),
    category: categories.fiction,
  },
  {
    id: "f-6",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: "199",
    image: "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-10"),
    category: categories.fiction,
  },
  {
    id: "f-7",
    title: "One Hundred Years of Solitude",
    author: "Gabriel Garcia Marquez",
    price: "459",
    image: "https://covers.openlibrary.org/b/isbn/9780060883287-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-09"),
    category: categories.fiction,
  },
  {
    id: "f-8",
    title: "Brave New World",
    author: "Aldous Huxley",
    price: "329",
    image: "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-08"),
    category: categories.fiction,
  },
  {
    id: "f-9",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    price: "289",
    image: "https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg",
    rating: 4.3,
    createdAt: new Date("2026-01-07"),
    category: categories.fiction,
  },
  {
    id: "f-10",
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    price: "399",
    image: "https://covers.openlibrary.org/b/isbn/9781594631931-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-06"),
    category: categories.fiction,
  },
  {
    id: "f-11",
    title: "Life of Pi",
    author: "Yann Martel",
    price: "349",
    image: "https://covers.openlibrary.org/b/isbn/9780156027328-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-05"),
    category: categories.fiction,
  },
  {
    id: "f-12",
    title: "The Book Thief",
    author: "Markus Zusak",
    price: "379",
    image: "https://covers.openlibrary.org/b/isbn/9780375842207-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-04"),
    category: categories.fiction,
  },
  {
    id: "f-13",
    title: "All the Light We Cannot See",
    author: "Anthony Doerr",
    price: "449",
    image: "https://covers.openlibrary.org/b/isbn/9781501173219-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-03"),
    category: categories.fiction,
  },
  {
    id: "f-14",
    title: "The Shadow of the Wind",
    author: "Carlos Ruiz Zafon",
    price: "499",
    image: "https://covers.openlibrary.org/b/isbn/9780143034902-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-02"),
    category: categories.fiction,
  },
  {
    id: "f-15",
    title: "A Man Called Ove",
    author: "Fredrik Backman",
    price: "359",
    image: "https://covers.openlibrary.org/b/isbn/9781476738024-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-01"),
    category: categories.fiction,
  },
  {
    id: "f-16",
    title: "Normal People",
    author: "Sally Rooney",
    price: "389",
    image: "https://covers.openlibrary.org/b/isbn/9781984822178-L.jpg",
    rating: 4.3,
    createdAt: new Date("2025-12-30"),
    category: categories.fiction,
  },
  {
    id: "f-17",
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    price: "429",
    image: "https://covers.openlibrary.org/b/isbn/9780735219090-L.jpg",
    rating: 4.7,
    createdAt: new Date("2025-12-29"),
    category: categories.fiction,
  },
  {
    id: "f-18",
    title: "Circe",
    author: "Madeline Miller",
    price: "419",
    image: "https://covers.openlibrary.org/b/isbn/9780316556347-L.jpg",
    rating: 4.5,
    createdAt: new Date("2025-12-28"),
    category: categories.fiction,
  },
  {
    id: "f-19",
    title: "The Night Circus",
    author: "Erin Morgenstern",
    price: "379",
    image: "https://covers.openlibrary.org/b/isbn/9780385534635-L.jpg",
    rating: 4.4,
    createdAt: new Date("2025-12-27"),
    category: categories.fiction,
  },
  {
    id: "f-20",
    title: "Beloved",
    author: "Toni Morrison",
    price: "339",
    image: "https://covers.openlibrary.org/b/isbn/9781400033416-L.jpg",
    rating: 4.5,
    createdAt: new Date("2025-12-26"),
    category: categories.fiction,
  },
  {
    id: "f-21",
    title: "The God of Small Things",
    author: "Arundhati Roy",
    price: "299",
    image: "https://covers.openlibrary.org/b/isbn/9780679457312-L.jpg",
    rating: 4.3,
    createdAt: new Date("2025-12-25"),
    category: categories.fiction,
  },
  {
    id: "f-22",
    title: "Pachinko",
    author: "Min Jin Lee",
    price: "469",
    image: "https://covers.openlibrary.org/b/isbn/9781455563920-L.jpg",
    rating: 4.6,
    createdAt: new Date("2025-12-24"),
    category: categories.fiction,
  },
  {
    id: "f-23",
    title: "The Remains of the Day",
    author: "Kazuo Ishiguro",
    price: "329",
    image: "https://covers.openlibrary.org/b/isbn/9780679731726-L.jpg",
    rating: 4.4,
    createdAt: new Date("2025-12-23"),
    category: categories.fiction,
  },
  {
    id: "f-24",
    title: "Shuggie Bain",
    author: "Douglas Stuart",
    price: "399",
    image: "https://covers.openlibrary.org/b/isbn/9780802148049-L.jpg",
    rating: 4.3,
    createdAt: new Date("2025-12-22"),
    category: categories.fiction,
  },
  {
    id: "f-25",
    title: "The Goldfinch",
    author: "Donna Tartt",
    price: "549",
    image: "https://covers.openlibrary.org/b/isbn/9780316055437-L.jpg",
    rating: 4.2,
    createdAt: new Date("2025-12-21"),
    category: categories.fiction,
  },
  {
    id: "f-26",
    title: "Cloud Cuckoo Land",
    author: "Anthony Doerr",
    price: "489",
    image: "https://covers.openlibrary.org/b/isbn/9781982168438-L.jpg",
    rating: 4.3,
    createdAt: new Date("2025-12-20"),
    category: categories.fiction,
  },
  {
    id: "f-27",
    title: "Hamnet",
    author: "Maggie O'Farrell",
    price: "369",
    image: "https://covers.openlibrary.org/b/isbn/9780525657606-L.jpg",
    rating: 4.5,
    createdAt: new Date("2025-12-19"),
    category: categories.fiction,
  },
  {
    id: "f-28",
    title: "Klara and the Sun",
    author: "Kazuo Ishiguro",
    price: "419",
    image: "https://covers.openlibrary.org/b/isbn/9780593318171-L.jpg",
    rating: 4.2,
    createdAt: new Date("2025-12-18"),
    category: categories.fiction,
  },
  {
    id: "f-29",
    title: "Black Cake",
    author: "Charmaine Wilkerson",
    price: "315",
    image: "https://covers.openlibrary.org/b/isbn/9780593358344-L.jpg",
    rating: 4.4,
    createdAt: new Date("2025-12-17"),
    category: categories.fiction,
  },
  {
    id: "f-30",
    title: "The Midnight Library",
    author: "Matt Haig",
    price: "389",
    image: "https://covers.openlibrary.org/b/isbn/9780525559474-L.jpg",
    rating: 4.5,
    createdAt: new Date("2025-12-16"),
    category: categories.fiction,
  },

  // ═══════════════════════════════════════════════════
  // NON-FICTION (25 books)
  // ═══════════════════════════════════════════════════
  {
    id: "nf-1",
    title: "Atomic Habits",
    author: "James Clear",
    price: "499",
    image: "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
    rating: 4.9,
    createdAt: new Date("2026-01-15"),
    category: categories.nonFiction,
  },
  {
    id: "nf-2",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    price: "549",
    image: "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-14"),
    category: categories.nonFiction,
  },
  {
    id: "nf-3",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    price: "399",
    image: "https://covers.openlibrary.org/b/isbn/9780857197689-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-13"),
    category: categories.nonFiction,
  },
  {
    id: "nf-4",
    title: "Deep Work",
    author: "Cal Newport",
    price: "429",
    image: "https://covers.openlibrary.org/b/isbn/9781455586691-L.jpg",
    rating: 4.8,
    createdAt: new Date("2026-01-12"),
    category: categories.nonFiction,
  },
  {
    id: "nf-5",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    price: "599",
    image: "https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-11"),
    category: categories.nonFiction,
  },
  {
    id: "nf-6",
    title: "Zero to One",
    author: "Peter Thiel",
    price: "459",
    image: "https://covers.openlibrary.org/b/isbn/9780804139298-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-10"),
    category: categories.nonFiction,
  },
  {
    id: "nf-7",
    title: "The Power of Now",
    author: "Eckhart Tolle",
    price: "349",
    image: "https://covers.openlibrary.org/b/isbn/9781577314806-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-09"),
    category: categories.nonFiction,
  },
  {
    id: "nf-8",
    title: "Educated",
    author: "Tara Westover",
    price: "449",
    image: "https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-08"),
    category: categories.nonFiction,
  },
  {
    id: "nf-9",
    title: "Man's Search for Meaning",
    author: "Viktor E. Frankl",
    price: "279",
    image: "https://covers.openlibrary.org/b/isbn/9780807014295-L.jpg",
    rating: 4.8,
    createdAt: new Date("2026-01-07"),
    category: categories.nonFiction,
  },
  {
    id: "nf-10",
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    price: "399",
    image: "https://covers.openlibrary.org/b/isbn/9780062457714-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-06"),
    category: categories.nonFiction,
  },
  {
    id: "nf-11",
    title: "Outliers",
    author: "Malcolm Gladwell",
    price: "379",
    image: "https://covers.openlibrary.org/b/isbn/9780316017930-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-05"),
    category: categories.nonFiction,
  },
  {
    id: "nf-12",
    title: "Guns, Germs, and Steel",
    author: "Jared Diamond",
    price: "529",
    image: "https://covers.openlibrary.org/b/isbn/9780393317558-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-04"),
    category: categories.nonFiction,
  },
  {
    id: "nf-13",
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen R. Covey",
    price: "419",
    image: "https://covers.openlibrary.org/b/isbn/9781982137274-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-03"),
    category: categories.nonFiction,
  },
  {
    id: "nf-14",
    title: "Ikigai",
    author: "Hector Garcia & Francesc Miralles",
    price: "299",
    image: "https://covers.openlibrary.org/b/isbn/9780143130727-L.jpg",
    rating: 4.3,
    createdAt: new Date("2026-01-02"),
    category: categories.nonFiction,
  },
  {
    id: "nf-15",
    title: "Range",
    author: "David Epstein",
    price: "449",
    image: "https://covers.openlibrary.org/b/isbn/9780735214484-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-01"),
    category: categories.nonFiction,
  },
  {
    id: "nf-16",
    title: "Quiet",
    author: "Susan Cain",
    price: "389",
    image: "https://covers.openlibrary.org/b/isbn/9780307352156-L.jpg",
    rating: 4.5,
    createdAt: new Date("2025-12-30"),
    category: categories.nonFiction,
  },
  {
    id: "nf-17",
    title: "The Body",
    author: "Bill Bryson",
    price: "479",
    image: "https://covers.openlibrary.org/b/isbn/9780385539302-L.jpg",
    rating: 4.5,
    createdAt: new Date("2025-12-29"),
    category: categories.nonFiction,
  },
  {
    id: "nf-18",
    title: "Why We Sleep",
    author: "Matthew Walker",
    price: "429",
    image: "https://covers.openlibrary.org/b/isbn/9781501144318-L.jpg",
    rating: 4.6,
    createdAt: new Date("2025-12-28"),
    category: categories.nonFiction,
  },
  {
    id: "nf-19",
    title: "Homo Deus",
    author: "Yuval Noah Harari",
    price: "519",
    image: "https://covers.openlibrary.org/b/isbn/9780062464316-L.jpg",
    rating: 4.5,
    createdAt: new Date("2025-12-27"),
    category: categories.nonFiction,
  },
  {
    id: "nf-20",
    title: "The Lean Startup",
    author: "Eric Ries",
    price: "459",
    image: "https://covers.openlibrary.org/b/isbn/9780307887894-L.jpg",
    rating: 4.4,
    createdAt: new Date("2025-12-26"),
    category: categories.nonFiction,
  },
  {
    id: "nf-21",
    title: "Grit",
    author: "Angela Duckworth",
    price: "389",
    image: "https://covers.openlibrary.org/b/isbn/9781501111105-L.jpg",
    rating: 4.4,
    createdAt: new Date("2025-12-25"),
    category: categories.nonFiction,
  },
  {
    id: "nf-22",
    title: "Freakonomics",
    author: "Steven D. Levitt",
    price: "349",
    image: "https://covers.openlibrary.org/b/isbn/9780060731335-L.jpg",
    rating: 4.3,
    createdAt: new Date("2025-12-24"),
    category: categories.nonFiction,
  },
  {
    id: "nf-23",
    title: "The Immortal Life of Henrietta Lacks",
    author: "Rebecca Skloot",
    price: "419",
    image: "https://covers.openlibrary.org/b/isbn/9781400052189-L.jpg",
    rating: 4.5,
    createdAt: new Date("2025-12-23"),
    category: categories.nonFiction,
  },
  {
    id: "nf-24",
    title: "Sapiens: A Graphic History",
    author: "Yuval Noah Harari",
    price: "699",
    image: "https://covers.openlibrary.org/b/isbn/9780063051331-L.jpg",
    rating: 4.3,
    createdAt: new Date("2025-12-22"),
    category: categories.nonFiction,
  },
  {
    id: "nf-25",
    title: "Think Again",
    author: "Adam Grant",
    price: "439",
    image: "https://covers.openlibrary.org/b/isbn/9781984878106-L.jpg",
    rating: 4.5,
    createdAt: new Date("2025-12-21"),
    category: categories.nonFiction,
  },

  // ═══════════════════════════════════════════════════
  // SCIENCE FICTION (25 books)
  // ═══════════════════════════════════════════════════
  {
    id: "sf-1",
    title: "Project Hail Mary",
    author: "Andy Weir",
    price: "499",
    image: "https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg",
    rating: 4.9,
    createdAt: new Date("2026-01-15"),
    category: categories.sciFi,
  },
  {
    id: "sf-2",
    title: "The Martian",
    author: "Andy Weir",
    price: "399",
    image: "https://covers.openlibrary.org/b/isbn/9780553418026-L.jpg",
    rating: 4.8,
    createdAt: new Date("2026-01-14"),
    category: categories.sciFi,
  },
  {
    id: "sf-3",
    title: "Ender's Game",
    author: "Orson Scott Card",
    price: "349",
    image: "https://covers.openlibrary.org/b/isbn/9780812550702-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-13"),
    category: categories.sciFi,
  },
  {
    id: "sf-4",
    title: "Foundation",
    author: "Isaac Asimov",
    price: "379",
    image: "https://covers.openlibrary.org/b/isbn/9780553293357-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-12"),
    category: categories.sciFi,
  },
  {
    id: "sf-5",
    title: "Neuromancer",
    author: "William Gibson",
    price: "329",
    image: "https://covers.openlibrary.org/b/isbn/9780441569595-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-11"),
    category: categories.sciFi,
  },
  {
    id: "sf-6",
    title: "The Left Hand of Darkness",
    author: "Ursula K. Le Guin",
    price: "299",
    image: "https://covers.openlibrary.org/b/isbn/9780441478125-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-10"),
    category: categories.sciFi,
  },
  {
    id: "sf-7",
    title: "Snow Crash",
    author: "Neal Stephenson",
    price: "419",
    image: "https://covers.openlibrary.org/b/isbn/9780553380958-L.jpg",
    rating: 4.3,
    createdAt: new Date("2026-01-09"),
    category: categories.sciFi,
  },
  {
    id: "sf-8",
    title: "The Three-Body Problem",
    author: "Liu Cixin",
    price: "459",
    image: "https://covers.openlibrary.org/b/isbn/9780765382030-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-08"),
    category: categories.sciFi,
  },
  {
    id: "sf-9",
    title: "Hyperion",
    author: "Dan Simmons",
    price: "389",
    image: "https://covers.openlibrary.org/b/isbn/9780553283686-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-07"),
    category: categories.sciFi,
  },
  {
    id: "sf-10",
    title: "2001: A Space Odyssey",
    author: "Arthur C. Clarke",
    price: "279",
    image: "https://covers.openlibrary.org/b/isbn/9780451457998-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-06"),
    category: categories.sciFi,
  },
  {
    id: "sf-11",
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    price: "249",
    image: "https://covers.openlibrary.org/b/isbn/9781451673319-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-05"),
    category: categories.sciFi,
  },
  {
    id: "sf-12",
    title: "Do Androids Dream of Electric Sheep?",
    author: "Philip K. Dick",
    price: "319",
    image: "https://covers.openlibrary.org/b/isbn/9780345404473-L.jpg",
    rating: 4.3,
    createdAt: new Date("2026-01-04"),
    category: categories.sciFi,
  },
  {
    id: "sf-13",
    title: "The Dispossessed",
    author: "Ursula K. Le Guin",
    price: "339",
    image: "https://covers.openlibrary.org/b/isbn/9780061054884-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-03"),
    category: categories.sciFi,
  },
  {
    id: "sf-14",
    title: "Dune Messiah",
    author: "Frank Herbert",
    price: "359",
    image: "https://covers.openlibrary.org/b/isbn/9780593098233-L.jpg",
    rating: 4.3,
    createdAt: new Date("2026-01-02"),
    category: categories.sciFi,
  },
  {
    id: "sf-15",
    title: "Children of Time",
    author: "Adrian Tchaikovsky",
    price: "429",
    image: "https://covers.openlibrary.org/b/isbn/9780316452502-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-01"),
    category: categories.sciFi,
  },
  {
    id: "sf-16",
    title: "The Hitchhiker's Guide to the Galaxy",
    author: "Douglas Adams",
    price: "289",
    image: "https://covers.openlibrary.org/b/isbn/9780345391803-L.jpg",
    rating: 4.7,
    createdAt: new Date("2025-12-30"),
    category: categories.sciFi,
  },
  {
    id: "sf-17",
    title: "Slaughterhouse-Five",
    author: "Kurt Vonnegut",
    price: "299",
    image: "https://covers.openlibrary.org/b/isbn/9780440180296-L.jpg",
    rating: 4.4,
    createdAt: new Date("2025-12-29"),
    category: categories.sciFi,
  },
  {
    id: "sf-18",
    title: "The War of the Worlds",
    author: "H.G. Wells",
    price: "199",
    image: "https://covers.openlibrary.org/b/isbn/9780141441030-L.jpg",
    rating: 4.2,
    createdAt: new Date("2025-12-28"),
    category: categories.sciFi,
  },
  {
    id: "sf-19",
    title: "Rendezvous with Rama",
    author: "Arthur C. Clarke",
    price: "329",
    image: "https://covers.openlibrary.org/b/isbn/9780553287899-L.jpg",
    rating: 4.4,
    createdAt: new Date("2025-12-27"),
    category: categories.sciFi,
  },
  {
    id: "sf-20",
    title: "Annihilation",
    author: "Jeff VanderMeer",
    price: "349",
    image: "https://covers.openlibrary.org/b/isbn/9780374104092-L.jpg",
    rating: 4.2,
    createdAt: new Date("2025-12-26"),
    category: categories.sciFi,
  },
  {
    id: "sf-21",
    title: "Recursion",
    author: "Blake Crouch",
    price: "399",
    image: "https://covers.openlibrary.org/b/isbn/9781524759780-L.jpg",
    rating: 4.5,
    createdAt: new Date("2025-12-25"),
    category: categories.sciFi,
  },
  {
    id: "sf-22",
    title: "Dark Matter",
    author: "Blake Crouch",
    price: "379",
    image: "https://covers.openlibrary.org/b/isbn/9781101904220-L.jpg",
    rating: 4.4,
    createdAt: new Date("2025-12-24"),
    category: categories.sciFi,
  },
  {
    id: "sf-23",
    title: "Exhalation",
    author: "Ted Chiang",
    price: "419",
    image: "https://covers.openlibrary.org/b/isbn/9781101947883-L.jpg",
    rating: 4.6,
    createdAt: new Date("2025-12-23"),
    category: categories.sciFi,
  },
  {
    id: "sf-24",
    title: "Leviathan Wakes",
    author: "James S.A. Corey",
    price: "449",
    image: "https://covers.openlibrary.org/b/isbn/9780316129084-L.jpg",
    rating: 4.5,
    createdAt: new Date("2025-12-22"),
    category: categories.sciFi,
  },
  {
    id: "sf-25",
    title: "Blindsight",
    author: "Peter Watts",
    price: "359",
    image: "https://covers.openlibrary.org/b/isbn/9780765319647-L.jpg",
    rating: 4.3,
    createdAt: new Date("2025-12-21"),
    category: categories.sciFi,
  },

  // ═══════════════════════════════════════════════════
  // FANTASY (25 books)
  // ═══════════════════════════════════════════════════
  {
    id: "fa-1",
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    price: "499",
    image: "https://covers.openlibrary.org/b/isbn/9780756404741-L.jpg",
    rating: 4.8,
    createdAt: new Date("2026-01-15"),
    category: categories.fantasy,
  },
  {
    id: "fa-2",
    title: "The Way of Kings",
    author: "Brandon Sanderson",
    price: "649",
    image: "https://covers.openlibrary.org/b/isbn/9780765365279-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-14"),
    category: categories.fantasy,
  },
  {
    id: "fa-3",
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    price: "549",
    image: "https://covers.openlibrary.org/b/isbn/9780553573404-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-13"),
    category: categories.fantasy,
  },
  {
    id: "fa-4",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    price: "399",
    image: "https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",
    rating: 4.8,
    createdAt: new Date("2026-01-12"),
    category: categories.fantasy,
  },
  {
    id: "fa-5",
    title: "The Fellowship of the Ring",
    author: "J.R.R. Tolkien",
    price: "499",
    image: "https://covers.openlibrary.org/b/isbn/9780547928210-L.jpg",
    rating: 4.8,
    createdAt: new Date("2026-01-11"),
    category: categories.fantasy,
  },
  {
    id: "fa-6",
    title: "Mistborn: The Final Empire",
    author: "Brandon Sanderson",
    price: "449",
    image: "https://covers.openlibrary.org/b/isbn/9780765311788-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-10"),
    category: categories.fantasy,
  },
  {
    id: "fa-7",
    title: "The Lies of Locke Lamora",
    author: "Scott Lynch",
    price: "419",
    image: "https://covers.openlibrary.org/b/isbn/9780553588941-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-09"),
    category: categories.fantasy,
  },
  {
    id: "fa-8",
    title: "The Fifth Season",
    author: "N.K. Jemisin",
    price: "389",
    image: "https://covers.openlibrary.org/b/isbn/9780316229296-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-08"),
    category: categories.fantasy,
  },
  {
    id: "fa-9",
    title: "The Blade Itself",
    author: "Joe Abercrombie",
    price: "379",
    image: "https://covers.openlibrary.org/b/isbn/9780316387316-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-07"),
    category: categories.fantasy,
  },
  {
    id: "fa-10",
    title: "Assassin's Apprentice",
    author: "Robin Hobb",
    price: "359",
    image: "https://covers.openlibrary.org/b/isbn/9780553573398-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-06"),
    category: categories.fantasy,
  },
  {
    id: "fa-11",
    title: "The Priory of the Orange Tree",
    author: "Samantha Shannon",
    price: "529",
    image: "https://covers.openlibrary.org/b/isbn/9781635570298-L.jpg",
    rating: 4.3,
    createdAt: new Date("2026-01-05"),
    category: categories.fantasy,
  },
  {
    id: "fa-12",
    title: "Piranesi",
    author: "Susanna Clarke",
    price: "349",
    image: "https://covers.openlibrary.org/b/isbn/9781635575798-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-04"),
    category: categories.fantasy,
  },
  {
    id: "fa-13",
    title: "The Poppy War",
    author: "R.F. Kuang",
    price: "419",
    image: "https://covers.openlibrary.org/b/isbn/9780062662569-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-03"),
    category: categories.fantasy,
  },
  {
    id: "fa-14",
    title: "Gardens of the Moon",
    author: "Steven Erikson",
    price: "459",
    image: "https://covers.openlibrary.org/b/isbn/9780765348784-L.jpg",
    rating: 4.3,
    createdAt: new Date("2026-01-02"),
    category: categories.fantasy,
  },
  {
    id: "fa-15",
    title: "American Gods",
    author: "Neil Gaiman",
    price: "429",
    image: "https://covers.openlibrary.org/b/isbn/9780063081918-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-01"),
    category: categories.fantasy,
  },
  {
    id: "fa-16",
    title: "The Witcher: The Last Wish",
    author: "Andrzej Sapkowski",
    price: "349",
    image: "https://covers.openlibrary.org/b/isbn/9780316029186-L.jpg",
    rating: 4.5,
    createdAt: new Date("2025-12-30"),
    category: categories.fantasy,
  },
  {
    id: "fa-17",
    title: "A Wizard of Earthsea",
    author: "Ursula K. Le Guin",
    price: "279",
    image: "https://covers.openlibrary.org/b/isbn/9780547722023-L.jpg",
    rating: 4.4,
    createdAt: new Date("2025-12-29"),
    category: categories.fantasy,
  },
  {
    id: "fa-18",
    title: "Words of Radiance",
    author: "Brandon Sanderson",
    price: "699",
    image: "https://covers.openlibrary.org/b/isbn/9780765326362-L.jpg",
    rating: 4.8,
    createdAt: new Date("2025-12-28"),
    category: categories.fantasy,
  },
  {
    id: "fa-19",
    title: "The Once and Future King",
    author: "T.H. White",
    price: "339",
    image: "https://covers.openlibrary.org/b/isbn/9780441627400-L.jpg",
    rating: 4.3,
    createdAt: new Date("2025-12-27"),
    category: categories.fantasy,
  },
  {
    id: "fa-20",
    title: "The Colour of Magic",
    author: "Terry Pratchett",
    price: "299",
    image: "https://covers.openlibrary.org/b/isbn/9780062225672-L.jpg",
    rating: 4.4,
    createdAt: new Date("2025-12-26"),
    category: categories.fantasy,
  },
  {
    id: "fa-21",
    title: "The House in the Cerulean Sea",
    author: "TJ Klune",
    price: "389",
    image: "https://covers.openlibrary.org/b/isbn/9781250217318-L.jpg",
    rating: 4.6,
    createdAt: new Date("2025-12-25"),
    category: categories.fantasy,
  },
  {
    id: "fa-22",
    title: "Babel",
    author: "R.F. Kuang",
    price: "519",
    image: "https://covers.openlibrary.org/b/isbn/9780063021426-L.jpg",
    rating: 4.5,
    createdAt: new Date("2025-12-24"),
    category: categories.fantasy,
  },
  {
    id: "fa-23",
    title: "The Atlas Six",
    author: "Olivie Blake",
    price: "429",
    image: "https://covers.openlibrary.org/b/isbn/9781250854513-L.jpg",
    rating: 4.2,
    createdAt: new Date("2025-12-23"),
    category: categories.fantasy,
  },
  {
    id: "fa-24",
    title: "Legends & Lattes",
    author: "Travis Baldree",
    price: "349",
    image: "https://covers.openlibrary.org/b/isbn/9781250886064-L.jpg",
    rating: 4.4,
    createdAt: new Date("2025-12-22"),
    category: categories.fantasy,
  },
  {
    id: "fa-25",
    title: "The Invisible Life of Addie LaRue",
    author: "V.E. Schwab",
    price: "439",
    image: "https://covers.openlibrary.org/b/isbn/9780765387561-L.jpg",
    rating: 4.3,
    createdAt: new Date("2025-12-21"),
    category: categories.fantasy,
  },

  // ═══════════════════════════════════════════════════
  // MYSTERY & THRILLER (25 books)
  // ═══════════════════════════════════════════════════
  {
    id: "mt-1",
    title: "Gone Girl",
    author: "Gillian Flynn",
    price: "399",
    image: "https://covers.openlibrary.org/b/isbn/9780307588371-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-15"),
    category: categories.mystery,
  },
  {
    id: "mt-2",
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    price: "449",
    image: "https://covers.openlibrary.org/b/isbn/9780307454546-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-14"),
    category: categories.mystery,
  },
  {
    id: "mt-3",
    title: "The Da Vinci Code",
    author: "Dan Brown",
    price: "379",
    image: "https://covers.openlibrary.org/b/isbn/9780307474278-L.jpg",
    rating: 4.3,
    createdAt: new Date("2026-01-13"),
    category: categories.mystery,
  },
  {
    id: "mt-4",
    title: "And Then There Were None",
    author: "Agatha Christie",
    price: "249",
    image: "https://covers.openlibrary.org/b/isbn/9780062073488-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-12"),
    category: categories.mystery,
  },
  {
    id: "mt-5",
    title: "The Girl on the Train",
    author: "Paula Hawkins",
    price: "359",
    image: "https://covers.openlibrary.org/b/isbn/9781594634024-L.jpg",
    rating: 4.2,
    createdAt: new Date("2026-01-11"),
    category: categories.mystery,
  },
  {
    id: "mt-6",
    title: "In the Woods",
    author: "Tana French",
    price: "389",
    image: "https://covers.openlibrary.org/b/isbn/9780143113492-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-10"),
    category: categories.mystery,
  },
  {
    id: "mt-7",
    title: "The Woman in the Window",
    author: "A.J. Finn",
    price: "379",
    image: "https://covers.openlibrary.org/b/isbn/9780062678416-L.jpg",
    rating: 4.1,
    createdAt: new Date("2026-01-09"),
    category: categories.mystery,
  },
  {
    id: "mt-8",
    title: "Big Little Lies",
    author: "Liane Moriarty",
    price: "399",
    image: "https://covers.openlibrary.org/b/isbn/9780399587191-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-08"),
    category: categories.mystery,
  },
  {
    id: "mt-9",
    title: "Sharp Objects",
    author: "Gillian Flynn",
    price: "339",
    image: "https://covers.openlibrary.org/b/isbn/9780307341556-L.jpg",
    rating: 4.3,
    createdAt: new Date("2026-01-07"),
    category: categories.mystery,
  },
  {
    id: "mt-10",
    title: "The Maid",
    author: "Nita Prose",
    price: "513",
    image: "https://covers.openlibrary.org/b/isbn/9780593356159-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-06"),
    category: categories.mystery,
  },
  {
    id: "mt-11",
    title: "Mexican Gothic",
    author: "Silvia Moreno-Garcia",
    price: "389",
    image: "https://covers.openlibrary.org/b/isbn/9780525620785-L.jpg",
    rating: 4.2,
    createdAt: new Date("2026-01-05"),
    category: categories.mystery,
  },
  {
    id: "mt-12",
    title: "The Thursday Murder Club",
    author: "Richard Osman",
    price: "429",
    image: "https://covers.openlibrary.org/b/isbn/9781984880963-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-04"),
    category: categories.mystery,
  },
  {
    id: "mt-13",
    title: "Verity",
    author: "Colleen Hoover",
    price: "349",
    image: "https://covers.openlibrary.org/b/isbn/9781538724736-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-03"),
    category: categories.mystery,
  },
  {
    id: "mt-14",
    title: "The Hunting Party",
    author: "Lucy Foley",
    price: "369",
    image: "https://covers.openlibrary.org/b/isbn/9780062868930-L.jpg",
    rating: 4.2,
    createdAt: new Date("2026-01-02"),
    category: categories.mystery,
  },
  {
    id: "mt-15",
    title: "The Maidens",
    author: "Alex Michaelides",
    price: "399",
    image: "https://covers.openlibrary.org/b/isbn/9781250304452-L.jpg",
    rating: 4.1,
    createdAt: new Date("2026-01-01"),
    category: categories.mystery,
  },
  {
    id: "mt-16",
    title: "One of Us Is Lying",
    author: "Karen M. McManus",
    price: "359",
    image: "https://covers.openlibrary.org/b/isbn/9781524714680-L.jpg",
    rating: 4.3,
    createdAt: new Date("2025-12-30"),
    category: categories.mystery,
  },
  {
    id: "mt-17",
    title: "The Silent House",
    author: "Nell Pattison",
    price: "319",
    image: "https://covers.openlibrary.org/b/isbn/9780008364526-L.jpg",
    rating: 4.2,
    createdAt: new Date("2025-12-29"),
    category: categories.mystery,
  },
  {
    id: "mt-18",
    title: "The Sanatorium",
    author: "Sarah Pearse",
    price: "389",
    image: "https://covers.openlibrary.org/b/isbn/9780593296677-L.jpg",
    rating: 4.1,
    createdAt: new Date("2025-12-28"),
    category: categories.mystery,
  },
  {
    id: "mt-19",
    title: "Rock Paper Scissors",
    author: "Alice Feeney",
    price: "369",
    image: "https://covers.openlibrary.org/b/isbn/9781250266101-L.jpg",
    rating: 4.2,
    createdAt: new Date("2025-12-27"),
    category: categories.mystery,
  },
  {
    id: "mt-20",
    title: "The It Girl",
    author: "Ruth Ware",
    price: "399",
    image: "https://covers.openlibrary.org/b/isbn/9781982155261-L.jpg",
    rating: 4.3,
    createdAt: new Date("2025-12-26"),
    category: categories.mystery,
  },
  {
    id: "mt-21",
    title: "The Paris Apartment",
    author: "Lucy Foley",
    price: "379",
    image: "https://covers.openlibrary.org/b/isbn/9780063003057-L.jpg",
    rating: 4.2,
    createdAt: new Date("2025-12-25"),
    category: categories.mystery,
  },
  {
    id: "mt-22",
    title: "The Last Thing He Told Me",
    author: "Laura Dave",
    price: "389",
    image: "https://covers.openlibrary.org/b/isbn/9781501171345-L.jpg",
    rating: 4.4,
    createdAt: new Date("2025-12-24"),
    category: categories.mystery,
  },
  {
    id: "mt-23",
    title: "Daisy Jones & The Six",
    author: "Taylor Jenkins Reid",
    price: "409",
    image: "https://covers.openlibrary.org/b/isbn/9781524798628-L.jpg",
    rating: 4.5,
    createdAt: new Date("2025-12-23"),
    category: categories.mystery,
  },
  {
    id: "mt-24",
    title: "The 7½ Deaths of Evelyn Hardcastle",
    author: "Stuart Turton",
    price: "419",
    image: "https://covers.openlibrary.org/b/isbn/9781492657965-L.jpg",
    rating: 4.3,
    createdAt: new Date("2025-12-22"),
    category: categories.mystery,
  },
  {
    id: "mt-25",
    title: "An Anonymous Girl",
    author: "Greer Hendricks",
    price: "359",
    image: "https://covers.openlibrary.org/b/isbn/9781250133731-L.jpg",
    rating: 4.1,
    createdAt: new Date("2025-12-21"),
    category: categories.mystery,
  },

  // ═══════════════════════════════════════════════════
  // ROMANCE (20 books)
  // ═══════════════════════════════════════════════════
  {
    id: "r-1",
    title: "It Ends with Us",
    author: "Colleen Hoover",
    price: "379",
    image: "https://covers.openlibrary.org/b/isbn/9781501110368-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-15"),
    category: categories.romance,
  },
  {
    id: "r-2",
    title: "The Love Hypothesis",
    author: "Ali Hazelwood",
    price: "399",
    image: "https://covers.openlibrary.org/b/isbn/9780593336823-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-14"),
    category: categories.romance,
  },
  {
    id: "r-3",
    title: "Beach Read",
    author: "Emily Henry",
    price: "359",
    image: "https://covers.openlibrary.org/b/isbn/9781984806734-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-13"),
    category: categories.romance,
  },
  {
    id: "r-4",
    title: "People We Meet on Vacation",
    author: "Emily Henry",
    price: "379",
    image: "https://covers.openlibrary.org/b/isbn/9781984806758-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-12"),
    category: categories.romance,
  },
  {
    id: "r-5",
    title: "The Hating Game",
    author: "Sally Thorne",
    price: "329",
    image: "https://covers.openlibrary.org/b/isbn/9780062439598-L.jpg",
    rating: 4.3,
    createdAt: new Date("2026-01-11"),
    category: categories.romance,
  },
  {
    id: "r-6",
    title: "Red, White & Royal Blue",
    author: "Casey McQuiston",
    price: "399",
    image: "https://covers.openlibrary.org/b/isbn/9781250316776-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-10"),
    category: categories.romance,
  },
  {
    id: "r-7",
    title: "The Spanish Love Deception",
    author: "Elena Armas",
    price: "389",
    image: "https://covers.openlibrary.org/b/isbn/9781668002520-L.jpg",
    rating: 4.3,
    createdAt: new Date("2026-01-09"),
    category: categories.romance,
  },
  {
    id: "r-8",
    title: "Book Lovers",
    author: "Emily Henry",
    price: "399",
    image: "https://covers.openlibrary.org/b/isbn/9780593334836-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-08"),
    category: categories.romance,
  },
  {
    id: "r-9",
    title: "The Notebook",
    author: "Nicholas Sparks",
    price: "279",
    image: "https://covers.openlibrary.org/b/isbn/9781455582877-L.jpg",
    rating: 4.3,
    createdAt: new Date("2026-01-07"),
    category: categories.romance,
  },
  {
    id: "r-10",
    title: "Outlander",
    author: "Diana Gabaldon",
    price: "549",
    image: "https://covers.openlibrary.org/b/isbn/9780440212560-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-06"),
    category: categories.romance,
  },
  {
    id: "r-11",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    price: "199",
    image: "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-05"),
    category: categories.romance,
  },
  {
    id: "r-12",
    title: "Me Before You",
    author: "Jojo Moyes",
    price: "349",
    image: "https://covers.openlibrary.org/b/isbn/9780143124542-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-04"),
    category: categories.romance,
  },
  {
    id: "r-13",
    title: "The Time Traveler's Wife",
    author: "Audrey Niffenegger",
    price: "399",
    image: "https://covers.openlibrary.org/b/isbn/9781476764832-L.jpg",
    rating: 4.3,
    createdAt: new Date("2026-01-03"),
    category: categories.romance,
  },
  {
    id: "r-14",
    title: "Ugly Love",
    author: "Colleen Hoover",
    price: "339",
    image: "https://covers.openlibrary.org/b/isbn/9781476753188-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-02"),
    category: categories.romance,
  },
  {
    id: "r-15",
    title: "November 9",
    author: "Colleen Hoover",
    price: "359",
    image: "https://covers.openlibrary.org/b/isbn/9781501110344-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-01"),
    category: categories.romance,
  },
  {
    id: "r-16",
    title: "The Flatshare",
    author: "Beth O'Leary",
    price: "369",
    image: "https://covers.openlibrary.org/b/isbn/9781250295637-L.jpg",
    rating: 4.3,
    createdAt: new Date("2025-12-30"),
    category: categories.romance,
  },
  {
    id: "r-17",
    title: "Happy Place",
    author: "Emily Henry",
    price: "419",
    image: "https://covers.openlibrary.org/b/isbn/9780593441275-L.jpg",
    rating: 4.4,
    createdAt: new Date("2025-12-29"),
    category: categories.romance,
  },
  {
    id: "r-18",
    title: "Things We Never Got Over",
    author: "Lucy Score",
    price: "389",
    image: "https://covers.openlibrary.org/b/isbn/9781728276304-L.jpg",
    rating: 4.4,
    createdAt: new Date("2025-12-28"),
    category: categories.romance,
  },
  {
    id: "r-19",
    title: "It Starts with Us",
    author: "Colleen Hoover",
    price: "399",
    image: "https://covers.openlibrary.org/b/isbn/9781668001226-L.jpg",
    rating: 4.3,
    createdAt: new Date("2025-12-27"),
    category: categories.romance,
  },
  {
    id: "r-20",
    title: "Love on the Brain",
    author: "Ali Hazelwood",
    price: "379",
    image: "https://covers.openlibrary.org/b/isbn/9780593336861-L.jpg",
    rating: 4.4,
    createdAt: new Date("2025-12-26"),
    category: categories.romance,
  },

  // ═══════════════════════════════════════════════════
  // BIOGRAPHY (20 books)
  // ═══════════════════════════════════════════════════
  {
    id: "b-1",
    title: "Becoming",
    author: "Michelle Obama",
    price: "599",
    image: "https://covers.openlibrary.org/b/isbn/9781524763138-L.jpg",
    rating: 4.8,
    createdAt: new Date("2026-01-15"),
    category: categories.biography,
  },
  {
    id: "b-2",
    title: "Steve Jobs",
    author: "Walter Isaacson",
    price: "649",
    image: "https://covers.openlibrary.org/b/isbn/9781451648539-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-14"),
    category: categories.biography,
  },
  {
    id: "b-3",
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    price: "249",
    image: "https://covers.openlibrary.org/b/isbn/9780553296983-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-13"),
    category: categories.biography,
  },
  {
    id: "b-4",
    title: "Born a Crime",
    author: "Trevor Noah",
    price: "449",
    image: "https://covers.openlibrary.org/b/isbn/9780399588174-L.jpg",
    rating: 4.8,
    createdAt: new Date("2026-01-12"),
    category: categories.biography,
  },
  {
    id: "b-5",
    title: "Long Walk to Freedom",
    author: "Nelson Mandela",
    price: "549",
    image: "https://covers.openlibrary.org/b/isbn/9780316548182-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-11"),
    category: categories.biography,
  },
  {
    id: "b-6",
    title: "The Autobiography of Malcolm X",
    author: "Malcolm X & Alex Haley",
    price: "379",
    image: "https://covers.openlibrary.org/b/isbn/9780345350688-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-10"),
    category: categories.biography,
  },
  {
    id: "b-7",
    title: "Einstein: His Life and Universe",
    author: "Walter Isaacson",
    price: "599",
    image: "https://covers.openlibrary.org/b/isbn/9780743264747-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-09"),
    category: categories.biography,
  },
  {
    id: "b-8",
    title: "Shoe Dog",
    author: "Phil Knight",
    price: "449",
    image: "https://covers.openlibrary.org/b/isbn/9781501135910-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-08"),
    category: categories.biography,
  },
  {
    id: "b-9",
    title: "When Breath Becomes Air",
    author: "Paul Kalanithi",
    price: "349",
    image: "https://covers.openlibrary.org/b/isbn/9780812988406-L.jpg",
    rating: 4.8,
    createdAt: new Date("2026-01-07"),
    category: categories.biography,
  },
  {
    id: "b-10",
    title: "The Glass Castle",
    author: "Jeannette Walls",
    price: "379",
    image: "https://covers.openlibrary.org/b/isbn/9780743247542-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-06"),
    category: categories.biography,
  },
  {
    id: "b-11",
    title: "Greenlights",
    author: "Matthew McConaughey",
    price: "429",
    image: "https://covers.openlibrary.org/b/isbn/9780593139134-L.jpg",
    rating: 4.3,
    createdAt: new Date("2026-01-05"),
    category: categories.biography,
  },
  {
    id: "b-12",
    title: "Elon Musk",
    author: "Walter Isaacson",
    price: "699",
    image: "https://covers.openlibrary.org/b/isbn/9781982181284-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-04"),
    category: categories.biography,
  },
  {
    id: "b-13",
    title: "I Know Why the Caged Bird Sings",
    author: "Maya Angelou",
    price: "299",
    image: "https://covers.openlibrary.org/b/isbn/9780345514400-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-03"),
    category: categories.biography,
  },
  {
    id: "b-14",
    title: "Can't Hurt Me",
    author: "David Goggins",
    price: "499",
    image: "https://covers.openlibrary.org/b/isbn/9781544512273-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-02"),
    category: categories.biography,
  },
  {
    id: "b-15",
    title: "A Promised Land",
    author: "Barack Obama",
    price: "749",
    image: "https://covers.openlibrary.org/b/isbn/9781524763169-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-01"),
    category: categories.biography,
  },
  {
    id: "b-16",
    title: "Dare to Lead",
    author: "Brene Brown",
    price: "419",
    image: "https://covers.openlibrary.org/b/isbn/9780399592522-L.jpg",
    rating: 4.5,
    createdAt: new Date("2025-12-30"),
    category: categories.biography,
  },
  {
    id: "b-17",
    title: "The Hard Thing About Hard Things",
    author: "Ben Horowitz",
    price: "449",
    image: "https://covers.openlibrary.org/b/isbn/9780062273208-L.jpg",
    rating: 4.4,
    createdAt: new Date("2025-12-29"),
    category: categories.biography,
  },
  {
    id: "b-18",
    title: "Principles",
    author: "Ray Dalio",
    price: "599",
    image: "https://covers.openlibrary.org/b/isbn/9781501124020-L.jpg",
    rating: 4.3,
    createdAt: new Date("2025-12-28"),
    category: categories.biography,
  },
  {
    id: "b-19",
    title: "My Experiments with Truth",
    author: "Mahatma Gandhi",
    price: "199",
    image: "https://covers.openlibrary.org/b/isbn/9780486245935-L.jpg",
    rating: 4.5,
    createdAt: new Date("2025-12-27"),
    category: categories.biography,
  },
  {
    id: "b-20",
    title: "Wings of Fire",
    author: "A.P.J. Abdul Kalam",
    price: "249",
    image: "https://covers.openlibrary.org/b/isbn/9788173711466-L.jpg",
    rating: 4.7,
    createdAt: new Date("2025-12-26"),
    category: categories.biography,
  },

  // ═══════════════════════════════════════════════════
  // TECHNOLOGY (25 books)
  // ═══════════════════════════════════════════════════
  {
    id: "t-1",
    title: "Clean Code",
    author: "Robert C. Martin",
    price: "699",
    image: "https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-15"),
    category: categories.technology,
  },
  {
    id: "t-2",
    title: "The Pragmatic Programmer",
    author: "David Thomas & Andrew Hunt",
    price: "649",
    image: "https://covers.openlibrary.org/b/isbn/9780135957059-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-14"),
    category: categories.technology,
  },
  {
    id: "t-3",
    title: "Design Patterns",
    author: "Gang of Four",
    price: "749",
    image: "https://covers.openlibrary.org/b/isbn/9780201633610-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-13"),
    category: categories.technology,
  },
  {
    id: "t-4",
    title: "You Don't Know JS Yet",
    author: "Kyle Simpson",
    price: "449",
    image: "https://covers.openlibrary.org/b/isbn/9781491904244-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-12"),
    category: categories.technology,
  },
  {
    id: "t-5",
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen",
    price: "899",
    image: "https://covers.openlibrary.org/b/isbn/9780262033848-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-11"),
    category: categories.technology,
  },
  {
    id: "t-6",
    title: "Cracking the Coding Interview",
    author: "Gayle Laakmann McDowell",
    price: "599",
    image: "https://covers.openlibrary.org/b/isbn/9780984782857-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-10"),
    category: categories.technology,
  },
  {
    id: "t-7",
    title: "System Design Interview",
    author: "Alex Xu",
    price: "549",
    image: "https://covers.openlibrary.org/b/isbn/9798664653403-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-09"),
    category: categories.technology,
  },
  {
    id: "t-8",
    title: "Refactoring",
    author: "Martin Fowler",
    price: "699",
    image: "https://covers.openlibrary.org/b/isbn/9780134757599-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-08"),
    category: categories.technology,
  },
  {
    id: "t-9",
    title: "Head First Design Patterns",
    author: "Eric Freeman",
    price: "579",
    image: "https://covers.openlibrary.org/b/isbn/9780596007126-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-07"),
    category: categories.technology,
  },
  {
    id: "t-10",
    title: "The Clean Coder",
    author: "Robert C. Martin",
    price: "599",
    image: "https://covers.openlibrary.org/b/isbn/9780137081073-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-06"),
    category: categories.technology,
  },
  {
    id: "t-11",
    title: "Learning Python",
    author: "Mark Lutz",
    price: "749",
    image: "https://covers.openlibrary.org/b/isbn/9781449355739-L.jpg",
    rating: 4.3,
    createdAt: new Date("2026-01-05"),
    category: categories.technology,
  },
  {
    id: "t-12",
    title: "Eloquent JavaScript",
    author: "Marijn Haverbeke",
    price: "499",
    image: "https://covers.openlibrary.org/b/isbn/9781593279509-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-04"),
    category: categories.technology,
  },
  {
    id: "t-13",
    title: "Code Complete",
    author: "Steve McConnell",
    price: "799",
    image: "https://covers.openlibrary.org/b/isbn/9780735619678-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-03"),
    category: categories.technology,
  },
  {
    id: "t-14",
    title: "Domain-Driven Design",
    author: "Eric Evans",
    price: "749",
    image: "https://covers.openlibrary.org/b/isbn/9780321125217-L.jpg",
    rating: 4.3,
    createdAt: new Date("2026-01-02"),
    category: categories.technology,
  },
  {
    id: "t-15",
    title: "Building Microservices",
    author: "Sam Newman",
    price: "649",
    image: "https://covers.openlibrary.org/b/isbn/9781492034025-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-01"),
    category: categories.technology,
  },
  {
    id: "t-16",
    title: "Designing Data-Intensive Applications",
    author: "Martin Kleppmann",
    price: "799",
    image: "https://covers.openlibrary.org/b/isbn/9781449373320-L.jpg",
    rating: 4.8,
    createdAt: new Date("2025-12-30"),
    category: categories.technology,
  },
  {
    id: "t-17",
    title: "The Phoenix Project",
    author: "Gene Kim",
    price: "499",
    image: "https://covers.openlibrary.org/b/isbn/9781942788294-L.jpg",
    rating: 4.5,
    createdAt: new Date("2025-12-29"),
    category: categories.technology,
  },
  {
    id: "t-18",
    title: "Site Reliability Engineering",
    author: "Google SRE Team",
    price: "699",
    image: "https://covers.openlibrary.org/b/isbn/9781491929124-L.jpg",
    rating: 4.4,
    createdAt: new Date("2025-12-28"),
    category: categories.technology,
  },
  {
    id: "t-19",
    title: "Grokking Algorithms",
    author: "Aditya Bhargava",
    price: "449",
    image: "https://covers.openlibrary.org/b/isbn/9781617292231-L.jpg",
    rating: 4.6,
    createdAt: new Date("2025-12-27"),
    category: categories.technology,
  },
  {
    id: "t-20",
    title: "Structure and Interpretation of Computer Programs",
    author: "Harold Abelson",
    price: "599",
    image: "https://covers.openlibrary.org/b/isbn/9780262510875-L.jpg",
    rating: 4.5,
    createdAt: new Date("2025-12-26"),
    category: categories.technology,
  },
  {
    id: "t-21",
    title: "The Art of Computer Programming",
    author: "Donald Knuth",
    price: "999",
    image: "https://covers.openlibrary.org/b/isbn/9780201896831-L.jpg",
    rating: 4.6,
    createdAt: new Date("2025-12-25"),
    category: categories.technology,
  },
  {
    id: "t-22",
    title: "Operating Systems: Three Easy Pieces",
    author: "Remzi H. Arpaci-Dusseau",
    price: "549",
    image: "https://covers.openlibrary.org/b/isbn/9781985086593-L.jpg",
    rating: 4.5,
    createdAt: new Date("2025-12-24"),
    category: categories.technology,
  },
  {
    id: "t-23",
    title: "Distributed Systems",
    author: "Maarten van Steen",
    price: "649",
    image: "https://covers.openlibrary.org/b/isbn/9781543057386-L.jpg",
    rating: 4.3,
    createdAt: new Date("2025-12-23"),
    category: categories.technology,
  },
  {
    id: "t-24",
    title: "Programming Pearls",
    author: "Jon Bentley",
    price: "449",
    image: "https://covers.openlibrary.org/b/isbn/9780201657883-L.jpg",
    rating: 4.4,
    createdAt: new Date("2025-12-22"),
    category: categories.technology,
  },
  {
    id: "t-25",
    title: "Compilers: Principles, Techniques, and Tools",
    author: "Alfred V. Aho",
    price: "849",
    image: "https://covers.openlibrary.org/b/isbn/9780321486813-L.jpg",
    rating: 4.3,
    createdAt: new Date("2025-12-21"),
    category: categories.technology,
  },

  // ═══════════════════════════════════════════════════
  // SCIENCE (15 books)
  // ═══════════════════════════════════════════════════
  {
    id: "sc-1",
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    price: "399",
    image: "https://covers.openlibrary.org/b/isbn/9780553380163-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-15"),
    category: categories.science,
  },
  {
    id: "sc-2",
    title: "The Selfish Gene",
    author: "Richard Dawkins",
    price: "449",
    image: "https://covers.openlibrary.org/b/isbn/9780198788607-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-14"),
    category: categories.science,
  },
  {
    id: "sc-3",
    title: "Cosmos",
    author: "Carl Sagan",
    price: "499",
    image: "https://covers.openlibrary.org/b/isbn/9780345539434-L.jpg",
    rating: 4.8,
    createdAt: new Date("2026-01-13"),
    category: categories.science,
  },
  {
    id: "sc-4",
    title: "Astrophysics for People in a Hurry",
    author: "Neil deGrasse Tyson",
    price: "299",
    image: "https://covers.openlibrary.org/b/isbn/9780393609394-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-12"),
    category: categories.science,
  },
  {
    id: "sc-5",
    title: "The Gene: An Intimate History",
    author: "Siddhartha Mukherjee",
    price: "549",
    image: "https://covers.openlibrary.org/b/isbn/9781476733524-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-11"),
    category: categories.science,
  },
  {
    id: "sc-6",
    title: "Surely You're Joking, Mr. Feynman!",
    author: "Richard P. Feynman",
    price: "379",
    image: "https://covers.openlibrary.org/b/isbn/9780393316049-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-10"),
    category: categories.science,
  },
  {
    id: "sc-7",
    title: "The Elegant Universe",
    author: "Brian Greene",
    price: "449",
    image: "https://covers.openlibrary.org/b/isbn/9780393338102-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-09"),
    category: categories.science,
  },
  {
    id: "sc-8",
    title: "The Origin of Species",
    author: "Charles Darwin",
    price: "299",
    image: "https://covers.openlibrary.org/b/isbn/9780451529060-L.jpg",
    rating: 4.3,
    createdAt: new Date("2026-01-08"),
    category: categories.science,
  },
  {
    id: "sc-9",
    title: "Silent Spring",
    author: "Rachel Carson",
    price: "329",
    image: "https://covers.openlibrary.org/b/isbn/9780618249060-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-07"),
    category: categories.science,
  },
  {
    id: "sc-10",
    title: "The Double Helix",
    author: "James D. Watson",
    price: "349",
    image: "https://covers.openlibrary.org/b/isbn/9780743216302-L.jpg",
    rating: 4.3,
    createdAt: new Date("2026-01-06"),
    category: categories.science,
  },
  {
    id: "sc-11",
    title: "What If?",
    author: "Randall Munroe",
    price: "399",
    image: "https://covers.openlibrary.org/b/isbn/9780544272996-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-05"),
    category: categories.science,
  },
  {
    id: "sc-12",
    title: "The Fabric of the Cosmos",
    author: "Brian Greene",
    price: "499",
    image: "https://covers.openlibrary.org/b/isbn/9780375727207-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-04"),
    category: categories.science,
  },
  {
    id: "sc-13",
    title: "Relativity",
    author: "Albert Einstein",
    price: "249",
    image: "https://covers.openlibrary.org/b/isbn/9780486417141-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-03"),
    category: categories.science,
  },
  {
    id: "sc-14",
    title: "The Emperor of All Maladies",
    author: "Siddhartha Mukherjee",
    price: "549",
    image: "https://covers.openlibrary.org/b/isbn/9781439170915-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-02"),
    category: categories.science,
  },
  {
    id: "sc-15",
    title: "Entangled Life",
    author: "Merlin Sheldrake",
    price: "419",
    image: "https://covers.openlibrary.org/b/isbn/9780525510314-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-01"),
    category: categories.science,
  },

  // ═══════════════════════════════════════════════════
  // YOUNG ADULT (20 books)
  // ═══════════════════════════════════════════════════
  {
    id: "ya-1",
    title: "The Hunger Games",
    author: "Suzanne Collins",
    price: "399",
    image: "https://covers.openlibrary.org/b/isbn/9780439023481-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-15"),
    category: categories.youngAdult,
  },
  {
    id: "ya-2",
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    price: "449",
    image: "https://covers.openlibrary.org/b/isbn/9780590353427-L.jpg",
    rating: 4.9,
    createdAt: new Date("2026-01-14"),
    category: categories.youngAdult,
  },
  {
    id: "ya-3",
    title: "The Fault in Our Stars",
    author: "John Green",
    price: "329",
    image: "https://covers.openlibrary.org/b/isbn/9780525478812-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-13"),
    category: categories.youngAdult,
  },
  {
    id: "ya-4",
    title: "Divergent",
    author: "Veronica Roth",
    price: "379",
    image: "https://covers.openlibrary.org/b/isbn/9780062024039-L.jpg",
    rating: 4.3,
    createdAt: new Date("2026-01-12"),
    category: categories.youngAdult,
  },
  {
    id: "ya-5",
    title: "The Maze Runner",
    author: "James Dashner",
    price: "349",
    image: "https://covers.openlibrary.org/b/isbn/9780385737951-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-11"),
    category: categories.youngAdult,
  },
  {
    id: "ya-6",
    title: "Percy Jackson: The Lightning Thief",
    author: "Rick Riordan",
    price: "369",
    image: "https://covers.openlibrary.org/b/isbn/9780786838653-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-10"),
    category: categories.youngAdult,
  },
  {
    id: "ya-7",
    title: "The Giver",
    author: "Lois Lowry",
    price: "249",
    image: "https://covers.openlibrary.org/b/isbn/9780544336261-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-09"),
    category: categories.youngAdult,
  },
  {
    id: "ya-8",
    title: "Twilight",
    author: "Stephenie Meyer",
    price: "349",
    image: "https://covers.openlibrary.org/b/isbn/9780316015844-L.jpg",
    rating: 4.2,
    createdAt: new Date("2026-01-08"),
    category: categories.youngAdult,
  },
  {
    id: "ya-9",
    title: "The Perks of Being a Wallflower",
    author: "Stephen Chbosky",
    price: "299",
    image: "https://covers.openlibrary.org/b/isbn/9781451696196-L.jpg",
    rating: 4.5,
    createdAt: new Date("2026-01-07"),
    category: categories.youngAdult,
  },
  {
    id: "ya-10",
    title: "Six of Crows",
    author: "Leigh Bardugo",
    price: "429",
    image: "https://covers.openlibrary.org/b/isbn/9781627792127-L.jpg",
    rating: 4.7,
    createdAt: new Date("2026-01-06"),
    category: categories.youngAdult,
  },
  {
    id: "ya-11",
    title: "The Hate U Give",
    author: "Angie Thomas",
    price: "379",
    image: "https://covers.openlibrary.org/b/isbn/9780062498533-L.jpg",
    rating: 4.6,
    createdAt: new Date("2026-01-05"),
    category: categories.youngAdult,
  },
  {
    id: "ya-12",
    title: "Children of Blood and Bone",
    author: "Tomi Adeyemi",
    price: "419",
    image: "https://covers.openlibrary.org/b/isbn/9781250170972-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-04"),
    category: categories.youngAdult,
  },
  {
    id: "ya-13",
    title: "Shadow and Bone",
    author: "Leigh Bardugo",
    price: "369",
    image: "https://covers.openlibrary.org/b/isbn/9781250027436-L.jpg",
    rating: 4.3,
    createdAt: new Date("2026-01-03"),
    category: categories.youngAdult,
  },
  {
    id: "ya-14",
    title: "City of Bones",
    author: "Cassandra Clare",
    price: "399",
    image: "https://covers.openlibrary.org/b/isbn/9781481455923-L.jpg",
    rating: 4.4,
    createdAt: new Date("2026-01-02"),
    category: categories.youngAdult,
  },
  {
    id: "ya-15",
    title: "Miss Peregrine's Home for Peculiar Children",
    author: "Ransom Riggs",
    price: "389",
    image: "https://covers.openlibrary.org/b/isbn/9781594746031-L.jpg",
    rating: 4.3,
    createdAt: new Date("2026-01-01"),
    category: categories.youngAdult,
  },
  {
    id: "ya-16",
    title: "A Court of Thorns and Roses",
    author: "Sarah J. Maas",
    price: "449",
    image: "https://covers.openlibrary.org/b/isbn/9781619634442-L.jpg",
    rating: 4.6,
    createdAt: new Date("2025-12-30"),
    category: categories.youngAdult,
  },
  {
    id: "ya-17",
    title: "The Selection",
    author: "Kiera Cass",
    price: "329",
    image: "https://covers.openlibrary.org/b/isbn/9780062059949-L.jpg",
    rating: 4.2,
    createdAt: new Date("2025-12-29"),
    category: categories.youngAdult,
  },
  {
    id: "ya-18",
    title: "Eragon",
    author: "Christopher Paolini",
    price: "399",
    image: "https://covers.openlibrary.org/b/isbn/9780375826696-L.jpg",
    rating: 4.4,
    createdAt: new Date("2025-12-28"),
    category: categories.youngAdult,
  },
  {
    id: "ya-19",
    title: "The Outsiders",
    author: "S.E. Hinton",
    price: "229",
    image: "https://covers.openlibrary.org/b/isbn/9780142407332-L.jpg",
    rating: 4.5,
    createdAt: new Date("2025-12-27"),
    category: categories.youngAdult,
  },
  {
    id: "ya-20",
    title: "Throne of Glass",
    author: "Sarah J. Maas",
    price: "419",
    image: "https://covers.openlibrary.org/b/isbn/9781619630345-L.jpg",
    rating: 4.5,
    createdAt: new Date("2025-12-26"),
    category: categories.youngAdult,
  },
];

export const demoCategories = Array.from(
  new Map(demoBooks.map((book) => [book.category.slug, book.category])).values(),
);
